IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [ONGS] (
    [ID] bigint NOT NULL IDENTITY,
    [NOME] nvarchar(100) NOT NULL,
    [CNPJ] nvarchar(20) NOT NULL,
    [EMAIL] nvarchar(150) NOT NULL,
    [TELEFONE] nvarchar(20) NOT NULL,
    CONSTRAINT [PK_ONGS] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [PONTOS_DE_ALIMENTO] (
    [ID] bigint NOT NULL IDENTITY,
    [NOME_LOCAL] nvarchar(100) NOT NULL,
    [ENDERECO] nvarchar(200) NOT NULL,
    [CAPACIDADE] int NOT NULL,
    CONSTRAINT [PK_PONTOS_DE_ALIMENTO] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [VOLUNTARIOS] (
    [ID] bigint NOT NULL IDENTITY,
    [NOME] nvarchar(100) NOT NULL,
    [TELEFONE] nvarchar(20) NOT NULL,
    [CIDADE] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_VOLUNTARIOS] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [ACOES_SOLIDARIAS] (
    [ID] bigint NOT NULL IDENTITY,
    [NOME] nvarchar(100) NOT NULL,
    [TIPO_EVENTO] nvarchar(50) NOT NULL,
    [CIDADE] nvarchar(100) NOT NULL,
    [ESTADO] nvarchar(50) NOT NULL,
    [DESCRICAO] nvarchar(300) NOT NULL,
    [META_ITENS] int NOT NULL,
    [ONG_ID] bigint NOT NULL,
    CONSTRAINT [PK_ACOES_SOLIDARIAS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_ACOES_SOLIDARIAS_ONGS_ONG_ID] FOREIGN KEY ([ONG_ID]) REFERENCES [ONGS] ([ID]) ON DELETE NO ACTION
);
GO

CREATE TABLE [DOACOES] (
    [ID] bigint NOT NULL IDENTITY,
    [TIPO] nvarchar(50) NOT NULL,
    [QUANTIDADE] int NOT NULL,
    [DATA_RECEBIDA] datetime2 NOT NULL,
    [ACAO_SOLIDARIA_ID] bigint NOT NULL,
    CONSTRAINT [PK_DOACOES] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_DOACOES_ACOES_SOLIDARIAS_ACAO_SOLIDARIA_ID] FOREIGN KEY ([ACAO_SOLIDARIA_ID]) REFERENCES [ACOES_SOLIDARIAS] ([ID]) ON DELETE NO ACTION
);
GO

CREATE TABLE [VOLUNTARIO_ACAO] (
    [VOLUNTARIO_ID] bigint NOT NULL,
    [ACAO_SOLIDARIA_ID] bigint NOT NULL,
    CONSTRAINT [PK_VOLUNTARIO_ACAO] PRIMARY KEY ([VOLUNTARIO_ID], [ACAO_SOLIDARIA_ID]),
    CONSTRAINT [FK_VOLUNTARIO_ACAO_ACOES_SOLIDARIAS_ACAO_SOLIDARIA_ID] FOREIGN KEY ([ACAO_SOLIDARIA_ID]) REFERENCES [ACOES_SOLIDARIAS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_VOLUNTARIO_ACAO_VOLUNTARIOS_VOLUNTARIO_ID] FOREIGN KEY ([VOLUNTARIO_ID]) REFERENCES [VOLUNTARIOS] ([ID]) ON DELETE CASCADE
);
GO

CREATE INDEX [IX_ACOES_SOLIDARIAS_ONG_ID] ON [ACOES_SOLIDARIAS] ([ONG_ID]);
GO

CREATE INDEX [IX_DOACOES_ACAO_SOLIDARIA_ID] ON [DOACOES] ([ACAO_SOLIDARIA_ID]);
GO

CREATE INDEX [IX_VOLUNTARIO_ACAO_ACAO_SOLIDARIA_ID] ON [VOLUNTARIO_ACAO] ([ACAO_SOLIDARIA_ID]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20251006133631_InitialSQLServerSchema', N'8.0.13');
GO

COMMIT;
GO

